---
vxlan:
  overlay:
    networks:
      - name: NaC-Net01
        vrf_name: NaC-VRF01
        net_id: 30001
        vlan_id: 2301
        vlan_name: NaC-Net01_vlan2301
        gw_ip_address: "10.10.1.1/24"
        network_attach_group: all
      - name: NaC-Net02
        vrf_name: NaC-VRF02
        net_id: 30002
        vlan_id: 2302
        vlan_name: NaC-Net02_vlan2302
        gw_ip_address: "92.68.2.2/24"
        network_attach_group: leaf3
      - name: NaC-Net03
        vrf_name: NaC-VRF03
        net_id: 30003
        vlan_id: 2303
        vlan_name: NaC-Net03_vlan2303
        gw_ip_address: "92.68.2.3/24"
        gw_ipv6_address: "2001::1/64"
        route_target_both: True
        l3gw_on_border: True
        mtu_l3intf: 7600
        int_desc: "Configured by NetAsCode"
        network_attach_group: leaf4
    network_attach_groups:
      - name: all
        switches:
          - { hostname: leaf1, ports: [port-channel10] }
          - { hostname: leaf2, ports: [port-channel10] }
      - name: leaf3
        switches:
          - { hostname: leaf3, ports: [] }
      - name: leaf4
        switches:
          - { hostname: leaf4, ports: [] }
